
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch:
  - platform: wake_on_lan
    mac: !secret lgtv_mac_address

webostv:
  host: 192.168.1.116
  name: LG TV
  turn_on_action:
    service: switch.turn_on
    target:
      entity_id: switch.wake_on_lan


fan:
  # Miki's room
  - platform: xiaomi_miio
    name: 'Miki Air Purifier'
    host: 192.168.1.119
    token: !secret xiaomi_air2_token
  # Bedroom
  - platform: xiaomi_miio
    name: 'Bedroom Air Purifier'
    host: 192.168.1.21
    token: !secret xiaomi_air3_token
    
ios:
  actions:
    - name: mytuner
      background_color: "#88423b"
      label:
        text: "Turn on myTuner"
        color: "#ffffff"
      icon:
        icon: radio
        color: "#ffffff"
    - name: bedtime
      background_color: "#38285c"
      label:
        text: "Good night"
        color: "#ffffff"
      icon:
        icon: weather-night
        color: "#ffffff"