
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

wake_on_lan:

webostv:
  host: 192.168.1.115
  name: LG65
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret lgtv_mac_address


fan:
  # Miki's room
  - platform: xiaomi_miio
    name: 'Miki Air Purifier'
    host: 192.168.1.119
    token: !secret xiaomi_air2_token
  # Bedroom
  - platform: xiaomi_miio
    name: 'Bedroom Air Purifier'
    host: 192.168.1.21
    token: !secret xiaomi_air3_token
    
ios:
  actions:
    - name: mytuner
      background_color: "#88423b"
      label:
        text: "Turn on myTuner"
        color: "#ffffff"
      icon:
        icon: radio
        color: "#ffffff"
    - name: bedtime
      background_color: "#38285c"
      label:
        text: "Good night"
        color: "#ffffff"
      icon:
        icon: weather-night
        color: "#ffffff"
    - name: tv_screen_off
      background_color: "#000000"
      label:
        text: "Screen Off"
        color: "#ffffff"
      icon:
        icon: tv-classic-off
        color: "#ffffff"
    - name: tv_screen_on
      background_color: "#000000"
      label:
        text: "Screen On"
        color: "#ffffff"
      icon:
        icon: tv-classic
        color: "#ffffff"
        

switch:
  - platform: wake_on_lan
    mac: !secret lgtv_mac_address
  - platform: template
    switches: 
      tv_screen:
        turn_on:
          - service: webostv.command
            data:
              entity_id: media_player.lg65
              command: com.webos.service.tvpower/power/turnOnScreen
        turn_off:
          - service: webostv.command
            data:
              entity_id: media_player.lg65
              command: com.webos.service.tvpower/power/turnOffScreen
              
template:
  - sensor:
      - name: "overheating"
        state: >
          {% set actual = state_attr('climate.thermostat_living_room', 'local_temperature') | float %}
          {% set desired = state_attr('climate.thermostat_living_room', 'current_heating_setpoint') | float %}

          {{ actual > desired }}


