
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch:
  - platform: wake_on_lan
    mac: !secret lgtv_mac_address

webostv:
  host: 192.168.1.116
  name: LG TV
  turn_on_action:
    service: switch.turn_on
    target:
      entity_id: switch.wake_on_lan

